<a href="https://colab.research.google.com/github/Shashank-Mittal/Machine-Learning-from-Basics-to-Advanced/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1: Linear Algebra Library
2: Numpy is like a building block for other libraries
3: Numpy is fast 

In [2]:
import numpy as np

Numpy array are of 2 types


1.   Vector 1-D array
2.   Metrices 2-D array



In [3]:
#Convert Python list to numpy array
my_list = [1,2,3]
np_arr = np.array(my_list)
print(np_arr,type(np_arr))

[1 2 3] <class 'numpy.ndarray'>


In [4]:
#Built in methods
print(np.arange(0,10))
print(np.zeros((1,7)))
print(np.ones((1,7)))
print(np.linspace(1,7,4))  # return number of values between specified interval
print(np.eye(4))


[0 1 2 3 4 5 6 7 8 9]
[[0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1.]]
[1. 3. 5. 7.]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**RANDOM**

In [5]:
print(np.random.rand(2,4))  #return uniform distribution
print(np.random.randn(2,4))  #return normal distribution
print(np.random.randint(0,50,10))  

[[0.23399155 0.24383271 0.30698563 0.38551023]
 [0.50736637 0.0080911  0.74077826 0.81675812]]
[[ 0.46664576  0.91325023 -1.7381615  -1.79459016]
 [-1.26635579 -0.82706455  0.46564612  0.92432094]]
[29 44 46 22 21  5 16  0 47 33]


**ATTRIBUTES**

In [6]:
arr = np.random.rand(2,4)

#Reshape
new_arr = arr.reshape(1,8)
print(new_arr)

print("Max: ", new_arr.max())
print("First index value of maxium value: ", new_arr.argmax())

print("Min: ", new_arr.min())
print("First index value of minimum value: ", new_arr.argmin())

[[0.93697067 0.31355729 0.65764991 0.64931223 0.73362314 0.56486838
  0.86764305 0.75900515]]
Max:  0.9369706685650228
First index value of maxium value:  0
Min:  0.31355729060429194
First index value of minimum value:  1


**Numpy Opertations**

In [7]:
arr_1 = np.arange(0,10)
arr_2 = np.arange(10,20)

diff = arr_2 - arr_1
sum_ = arr_2 + arr_1
multiplication_ = arr_2 * arr_1
divide = arr_2 / arr_1

print(sum_)
print(diff)
print(multiplication_)
print(divide)

[10 12 14 16 18 20 22 24 26 28]
[10 10 10 10 10 10 10 10 10 10]
[  0  11  24  39  56  75  96 119 144 171]
[        inf 11.          6.          4.33333333  3.5         3.
  2.66666667  2.42857143  2.25        2.11111111]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in true_divide
  import sys


**Universal Array Functions**

In [8]:
print(np.sqrt(arr_1))
print(np.log(arr_1))
print(np.sin(arr_1))
print(np.exp(arr_1))


[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


**Indexing and Slicing**

In [14]:
print(arr_1[0])
print(arr_1[0:])

0
[0 1 2 3 4 5 6 7 8 9]


**Selection**

In [15]:
arr_1>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])